from dataclasses import dataclass


@dataclass(frozen=True)
class TaxonomyRule:
    """A configurable parent pain point and the child signals that roll up to it.

    Add a rule or extend ``patterns`` to evolve the taxonomy. The grouping engine
    intentionally knows nothing about individual datasets, ticket IDs, or counts.
    """

    name: str
    description: str
    patterns: tuple[str, ...]
    category_aliases: tuple[str, ...] = ()
    excludes: tuple[str, ...] = ()


@dataclass(frozen=True)
class TaxonomyRuleV2:
    name: str
    description: str
    includes: tuple[str, ...]
    contexts: tuple[str, ...] = ()
    excludes: tuple[str, ...] = ()
    record_types: tuple[str, ...] = ()
    subcategories: tuple[str, ...] = ()
    assignment_hints: tuple[str, ...] = ()


LEGACY_DEFAULT_TAXONOMY = (
    TaxonomyRule(
        "Password Reset & Account Recovery Issues",
        "Users cannot recover accounts or complete password reset and unlock flows.",
        (
            "password reset", "reset link", "reset email", "temporary password",
            "account recovery", "security question", "lockout after reset",
            "set new password", "cannot set new", "cannot set a new", "forgot password", "reset password page",
            "temporary password",
        ),
    ),
    TaxonomyRule(
        "Access Provisioning & Authorization Issues",
        "Users have missing, delayed, or incorrect permissions, roles, entitlements, or group access.",
        (
            "permission", "access denied", "authorization", "role", "entitlement",
            "provisioning", "group membership", "access review", "access certification",
            "privileged access", "missing access", "access mismatch", "license assigned",
            "feature access", "licensed feature",
        ),
    ),
    TaxonomyRule(
        "Login & Authentication Failures",
        "Users cannot authenticate or maintain sessions because login, identity-provider, credential, or token validation fails.",
        (
            "login", "authentication", "session", "credentials", "credential", "token",
            "sso", "mfa", "oidc", "saml", "login page", "sign in", "signin", "account lockout",
            "locked account", "invalid password",
        ),
        ("access", "identity"),
    ),
    TaxonomyRule(
        "Security Alerts & Policy Violations",
        "Security operations are handling malware, phishing, suspicious activity, access-review, and policy alerts.",
        (
            "malware", "phishing", "suspicious login", "suspicious sign in", "policy violation",
            "antivirus", "quarantine", "blocked file transfer", "unauthorized software",
            "sensitive data", "unusual login", "multiple failed login", "failed login alert",
            "security monitoring", "access review alert", "privileged access review",
        ),
        ("security", "cyber security"),
    ),
    TaxonomyRule(
        "Database Reliability & Performance",
        "Database services are affected by connectivity, replication, query, capacity, or concurrency failures.",
        (
            "database connection", "connection pool", "query timeout", "query execution",
            "replication lag", "replication delay", "replica", "deadlock", "storage throttling", "database",
            "report query", "slow query", "database login",
        ),
        ("database", "data platform"),
    ),
    TaxonomyRule(
        "Integration & API Failures",
        "Integrations are disrupted by API, webhook, queue, OAuth, client-credential, or payload validation failures.",
        (
            "api failure", "api timeout", "api returning", "external api", "webhook",
            "queue delay", "queue backlog", "queue consumer", "message queue", "message backlog",
            "message processing", "oauth", "oauth token", "client credentials",
            "payload validation", "payload field", "schema validation", "contract mismatch",
            "integration authentication",
        ),
        ("integration", "api", "middleware"),
    ),
    TaxonomyRule(
        "Network Connectivity Issues",
        "Users and services experience DNS, VPN, firewall, WiFi, latency, routing, or outbound connectivity problems.",
        (
            "dns", "vpn", "firewall", "wifi", "wi fi", "latency", "route instability",
            "route unstable", "traffic denied", "traffic not routing", "outbound connection",
            "network connectivity", "captive portal",
        ),
        ("network", "connectivity"),
    ),
    TaxonomyRule(
        "Cloud Infrastructure Stability",
        "Cloud infrastructure is affected by compute, orchestration, load-balancing, secret, certificate, or storage instability.",
        (
            "cpu", "vm cpu", "vm restart", "instance restart", "compute", "kubernetes", "node pressure",
            "load balancer", "secret expiry", "secret expired", "secret rotation", "certificate",
            "storage throttling", "storage account", "cloud storage", "bucket permission", "blob upload", "auto scaling",
        ),
        ("cloud", "infrastructure", "platform"),
    ),
    TaxonomyRule(
        "Application Errors & Data Issues",
        "Applications have transaction, user-interface, performance, session, reporting, or data-consistency failures.",
        (
            "application error", "unhandled exception", "transaction error", "page load",
            "ui issue", "button not responding", "dropdown", "chart not rendering", "dashboard",
            "data mismatch", "missing records", "export", "slow performance", "batch job",
        ),
        ("software", "application"),
    ),
    TaxonomyRule(
        "End-User Hardware Issues",
        "Employees are affected by laptop, display, scanner, keyboard, battery, peripheral, or docking failures.",
        (
            "laptop", "keyboard", "monitor", "scanner", "scan quality", "document feeder",
            "peripheral", "docking", "mouse", "usb device", "battery", "screen goes blank",
            "display goes blank", "display not detected",
        ),
        ("hardware", "endpoint"),
    ),
)

DEFAULT_TAXONOMY_V2 = (
    TaxonomyRuleV2(
        name="Password Reset & Account Recovery Issues",
        description="Password reset, account recovery, unlock, reset link, temporary password, and recovery challenge failures.",
        includes=(
            "password reset", "reset password", "forgot password", "reset link", "reset email",
            "temporary password", "temp password", "one time password", "otp not received",
            "account recovery", "recover account", "security question", "recovery question",
            "unlock account", "account unlock", "locked after reset", "cannot set password",
            "set new password", "password expired", "password change failed",
            "reset email not received", "reset link expired", "temporary password rejected",
            "password policy", "password complexity", "password not accepted",
        ),
        contexts=("identity", "iam", "authentication", "user account", "active directory", "azure ad", "entra"),
        excludes=("database password", "service account password", "api key", "secret rotation"),
        record_types=("incident", "service_request"),
        subcategories=("reset_link", "otp", "account_unlock", "password_expiry", "recovery_questions"),
        assignment_hints=("IAM", "Identity", "Service Desk"),
    ),
    TaxonomyRuleV2(
        name="Login, SSO & Session Authentication Failures",
        description="User or system authentication failures involving login, SSO, MFA, SAML/OIDC, sessions, cookies, and token validation.",
        includes=(
            "login failed", "cannot login", "can't login", "unable to login", "sign in failed",
            "signin failed", "authentication failed", "invalid credentials", "invalid password",
            "account locked", "locked account", "too many failed attempts", "session expired",
            "session timeout", "keeps logging out", "logout issue", "token validation failed",
            "token validation error", "oidc token validation",
            "invalid token", "expired token", "jwt", "refresh token", "id token",
            "login", "login page", "sign in", "signin", "session expires", "session expires immediately",
            "account lockout", "sso", "sso failed", "sso redirect", "sso redirect failure", "single sign on", "saml", "oidc", "openid connect",
            "identity provider", "idp", "service provider", "sp initiated", "metadata mismatch",
            "assertion failed", "saml assertion rejected", "claim missing", "mfa failed", "mfa prompt",
            "mfa", "mfa enrollment", "mfa push", "mfa push not received", "authenticator app",
            "conditional access", "device compliance", "remember me not working",
        ),
        contexts=("identity", "iam", "sso", "authentication", "entra", "azure ad", "okta", "ping", "adfs"),
        excludes=("api token", "oauth client credentials", "database login", "login to database"),
        record_types=("incident", "alert"),
        subcategories=("sso", "mfa", "session", "token", "saml_oidc", "conditional_access"),
        assignment_hints=("IAM", "SSO", "Identity Provider"),
    ),
    TaxonomyRuleV2(
        name="Access Provisioning, Authorization & Licensing Issues",
        description="Missing, delayed, incorrect, or denied access involving roles, permissions, groups, entitlements, licenses, and approvals.",
        includes=(
            "access denied", "permission denied", "not authorized", "unauthorized",
            "missing access", "need access", "request access", "access request",
            "access not provisioned", "provisioning failed", "provisioning delay",
            "provisioning delayed", "role provisioning", "role provisioning delayed",
            "deprovisioning failed", "role missing", "incorrect role", "role mismatch",
            "entitlement", "group membership", "ad group", "security group",
            "access approval", "approval pending", "manager approval", "license assigned",
            "license missing", "licensed feature", "feature access", "rbac", "acl",
            "privileged access", "pam", "break glass", "elevated access",
        ),
        contexts=("iam", "identity", "authorization", "access", "access management", "active directory", "entra", "okta"),
        excludes=("network access", "website inaccessible", "page access error", "database connection"),
        record_types=("incident", "service_request"),
        subcategories=("missing_access", "role_group", "license", "approval", "pam", "deprovisioning"),
        assignment_hints=("IAM", "Access Management", "Service Desk"),
    ),
    TaxonomyRuleV2(
        name="Security Alerts, Threats & Compliance Violations",
        description="Security operations tickets for phishing, malware, suspicious activity, DLP, vulnerability, policy, compliance, and access review alerts.",
        includes=(
            "phishing", "malware", "ransomware", "virus detected", "trojan", "spyware",
            "suspicious login", "suspicious sign in", "impossible travel", "unusual login",
            "multiple failed login", "brute force", "credential stuffing",
            "security alert", "siem alert", "edr alert", "xdr alert", "soc alert",
            "antivirus", "quarantine", "blocked file", "blocked file transfer",
            "dlp", "data loss prevention", "sensitive data", "data leakage",
            "policy violation", "compliance violation", "unauthorized software",
            "vulnerability", "critical vulnerability", "cve", "patch compliance",
            "access review", "access review alert", "privileged access review", "certification overdue",
            "suspicious inbox rule", "mail forwarding rule", "compromised account",
        ),
        contexts=("security", "cyber security", "soc", "compliance", "risk", "audit"),
        excludes=("password reset", "normal access request", "license request"),
        record_types=("incident", "alert"),
        subcategories=("phishing", "malware", "dlp", "siem", "vulnerability", "policy", "compromised_account"),
        assignment_hints=("SOC", "Cyber Security", "Security Operations"),
    ),
    TaxonomyRuleV2(
        name="Email, Collaboration & Messaging Issues",
        description="Email, mailbox, calendar, Teams/Slack/Zoom, distribution list, mail routing, spam, attachment, and collaboration tool failures.",
        includes=(
            "email not received", "email not delivered", "mail delivery failed", "bounce back",
            "mailbox full", "shared mailbox", "distribution list", "dl update",
            "calendar invite", "meeting invite", "outlook", "exchange", "office 365",
            "o365", "m365", "mail routing", "smtp", "imap", "pop3", "autodiscover",
            "spam quarantine", "junk mail", "email attachment blocked", "attachment missing",
            "teams not working", "microsoft teams", "slack", "zoom", "webex",
            "chat not working", "presence not updating", "cannot join meeting",
        ),
        contexts=("email", "collaboration", "messaging", "m365", "exchange", "outlook"),
        excludes=("phishing", "suspicious email", "dlp"),
        record_types=("incident", "service_request"),
        subcategories=("mail_delivery", "mailbox", "calendar", "teams_slack_zoom", "distribution_list"),
        assignment_hints=("Messaging", "M365", "Collaboration"),
    ),
    TaxonomyRuleV2(
        name="Database Reliability & Performance",
        description="Database availability, connectivity, query, locking, replication, backup, storage, schema, and capacity issues.",
        includes=(
            "database connection", "db connection", "connection pool", "connection refused",
            "database unavailable", "db down", "database down", "database login failed",
            "query timeout", "slow query", "long running query", "query execution",
            "deadlock", "blocking session", "lock wait", "high db cpu", "db cpu",
            "replication lag", "replication delay", "replica lag", "read replica",
            "replica", "replica not catching up", "report query",
            "database storage full", "tablespace full", "transaction log full",
            "index fragmentation", "missing index", "schema migration failed",
            "stored procedure failed", "view failed", "database backup failed",
            "restore failed", "sql error", "oracle error", "postgres", "mysql",
            "mssql", "sql server", "cosmos db", "dynamodb", "mongodb", "redis cache",
        ),
        contexts=("database", "data platform", "sql", "db", "dba"),
        excludes=("application login", "user login", "api timeout", "network timeout"),
        record_types=("incident", "alert"),
        subcategories=("connectivity", "query_performance", "locking", "replication", "storage", "backup_restore", "schema"),
        assignment_hints=("DBA", "Database", "Data Platform"),
    ),
    TaxonomyRuleV2(
        name="Data Quality, Reporting & Analytics Issues",
        description="Incorrect, missing, stale, duplicate, delayed, or inconsistent data in reports, dashboards, exports, analytics, ETL, or business views.",
        includes=(
            "data mismatch", "missing data", "missing records", "incorrect data",
            "wrong data", "duplicate records", "stale data", "data not refreshed",
            "report mismatch", "report not matching", "dashboard mismatch",
            "dashboard not updated", "chart not rendering", "kpi mismatch",
            "export failed", "excel export", "csv export", "pdf export",
            "etl failed", "data pipeline failed", "pipeline delay", "data load failed",
            "ingestion failed", "sync failed", "reconciliation failed",
            "report query", "chart not rendering",
            "aggregation mismatch", "count mismatch", "filter not working",
        ),
        contexts=("reporting", "analytics", "dashboard", "bi", "data warehouse", "etl"),
        excludes=("access denied", "permission denied", "login failed"),
        record_types=("incident", "service_request"),
        subcategories=("missing_data", "incorrect_data", "report_export", "dashboard", "etl_pipeline", "reconciliation"),
        assignment_hints=("Data", "BI", "Reporting", "Analytics"),
    ),
    TaxonomyRuleV2(
        name="Integration, API & Middleware Failures",
        description="REST/API, webhook, OAuth client credentials, queues, middleware, schema, payload, vendor integration, and downstream dependency failures.",
        includes=(
            "api failure", "api failed", "api timeout", "api returning", "api error",
            "http 400", "http 401", "http 403", "http 404", "http 409",
            "http 429", "http 500", "http 502", "http 503", "http 504",
            "rest api", "graphql", "external api", "downstream error",
            "upstream error", "integration failed", "integration error",
            "webhook failed", "webhook not received", "webhook retries", "webhook retries exhausted", "callback failed",
            "queue delay", "queue backlog", "queue consumer", "message queue",
            "message backlog", "message processing failed", "kafka", "rabbitmq",
            "service bus", "sqs", "sns", "event hub", "dead letter queue", "dlq",
            "oauth token", "client credentials", "client secret", "api key",
            "payload validation", "payload error", "schema validation", "json schema validation", "contract mismatch",
            "field missing in payload", "serialization error", "deserialization error",
            "rate limit", "throttled", "circuit breaker",
        ),
        contexts=("integration", "api", "middleware", "interface", "connector", "adapter"),
        excludes=("user login", "mfa", "browser session", "database connection"),
        record_types=("incident", "alert"),
        subcategories=("api_http", "webhook", "queue_stream", "oauth_client", "payload_schema", "rate_limit", "vendor_dependency"),
        assignment_hints=("Integration", "Middleware", "API Platform"),
    ),
    TaxonomyRuleV2(
        name="Network, VPN, DNS & Firewall Issues",
        description="Network connectivity issues involving DNS, VPN, firewall, proxy, Wi-Fi, routing, latency, packet loss, and outbound/inbound traffic.",
        includes=(
            "network connectivity", "network issue", "cannot connect", "connection timeout",
            "connection refused", "dns", "dns resolution", "name resolution",
            "vpn", "vpn disconnected", "vpn not connecting", "globalprotect", "zscaler",
            "firewall", "traffic denied", "port blocked", "allowlist", "whitelist",
            "proxy", "proxy error", "pac file", "ssl inspection",
            "wifi", "wi fi", "wireless", "lan", "wan", "dhcp", "ip conflict",
            "ip address", "subnet", "routing", "route instability", "packet loss",
            "high latency", "latency", "jitter", "bandwidth", "captive portal",
            "outbound connection", "inbound connection", "tls handshake",
            "vpn latency", "corporate wifi", "firewall blocks outbound connection",
        ),
        contexts=("network", "connectivity", "firewall", "vpn", "dns", "proxy"),
        excludes=("database connection pool", "api payload", "application error"),
        record_types=("incident", "service_request", "alert"),
        subcategories=("dns", "vpn", "firewall_proxy", "wifi_lan", "routing_latency", "port_connectivity"),
        assignment_hints=("Network", "Firewall", "Connectivity"),
    ),
    TaxonomyRuleV2(
        name="Cloud, Compute & Container Platform Stability",
        description="Cloud platform, VM, Kubernetes, container, load balancer, autoscaling, node pressure, pod restart, and orchestration issues.",
        includes=(
            "vm restart", "instance restart", "server restart", "compute issue",
            "vm cpu", "high cpu", "cpu utilization", "memory pressure", "out of memory",
            "oomkilled", "disk pressure", "node pressure", "node not ready",
            "kubernetes", "k8s", "pod crash", "crashloopbackoff", "imagepullbackoff",
            "container restart", "deployment failed", "replica unavailable",
            "autoscaling", "auto scaling", "hpa", "cluster issue",
            "load balancer", "alb", "nlb", "ingress", "ingress controller",
            "health check failed", "availability zone", "region outage",
            "cloud outage", "cloud storage", "blob upload", "aws", "azure", "gcp", "eks", "aks", "gke",
        ),
        contexts=("cloud", "infrastructure", "platform", "kubernetes", "container", "compute"),
        excludes=("database cpu", "user laptop cpu", "application button not working"),
        record_types=("incident", "alert"),
        subcategories=("compute", "kubernetes", "container", "load_balancer", "autoscaling", "cloud_outage"),
        assignment_hints=("Cloud", "Platform", "SRE", "Infrastructure"),
    ),
    TaxonomyRuleV2(
        name="Storage, Backup & File Transfer Issues",
        description="Storage capacity, file upload/download, object storage, permissions, backup/restore, SFTP, and file movement issues.",
        includes=(
            "storage full", "disk full", "volume full", "mount issue", "file system full",
            "storage throttling", "storage account", "blob storage", "s3", "bucket",
            "bucket permission", "object storage", "file upload failed", "upload failed",
            "download failed", "file transfer failed", "sftp failed", "ftp failed",
            "file not found", "shared drive", "network drive", "nas", "san",
            "backup failed", "restore failed", "snapshot failed", "retention policy",
            "archive failed", "file permission", "cannot access folder",
        ),
        contexts=("storage", "backup", "file transfer", "sftp", "object storage"),
        excludes=("database storage full", "email attachment blocked"),
        record_types=("incident", "service_request", "alert"),
        subcategories=("capacity", "object_storage", "file_transfer", "backup_restore", "permissions"),
        assignment_hints=("Storage", "Backup", "Infrastructure"),
    ),
    TaxonomyRuleV2(
        name="Certificate, Secrets & Key Management Issues",
        description="Certificate expiry, secret rotation, key vault, keystore, truststore, TLS/SSL certificate, and credential expiry issues.",
        includes=(
            "certificate expired", "cert expired", "certificate expiry", "cert expiry",
            "ssl certificate", "tls certificate", "certificate renewal",
            "certificate chain", "truststore", "keystore", "private key",
            "secret expired", "secret expiry", "secret rotation", "client secret expired",
            "api secret", "key vault", "secrets manager", "kms", "hsm",
            "token signing certificate", "saml certificate", "oidc certificate",
            "mTLS", "mutual tls", "handshake failure",
        ),
        contexts=("certificate", "secret", "key management", "security", "platform"),
        excludes=("password reset", "user password expired"),
        record_types=("incident", "service_request", "alert", "change"),
        subcategories=("certificate_expiry", "secret_rotation", "key_vault", "truststore_keystore", "mtls"),
        assignment_hints=("Platform", "Security", "IAM", "Infrastructure"),
    ),
    TaxonomyRuleV2(
        name="Application Errors, Workflow & Functional Breakage",
        description="Application-level failures, exceptions, broken user journeys, transaction failures, business rule issues, and workflow errors.",
        includes=(
            "application error", "app error", "unhandled exception", "exception occurred",
            "null reference", "stack trace", "transaction failed", "transaction error",
            "business rule failed", "workflow failed", "approval workflow failed",
            "form submission failed", "submit button not working", "button not responding",
            "dropdown not loading", "page load failed", "page not loading",
            "screen freeze", "white screen", "blank page", "navigation issue",
            "search not working", "filter not working", "validation error",
            "calculation error", "rule engine", "case creation failed",
            "ticket creation failed", "order failed", "checkout failed",
            "ui issue", "slow performance", "performance issue", "login issue",
        ),
        contexts=("application", "software", "portal", "frontend", "backend", "workflow"),
        excludes=("login failed", "access denied", "database connection", "network connectivity"),
        record_types=("incident", "service_request"),
        subcategories=("exception", "ui", "workflow", "transaction", "validation", "business_rule"),
        assignment_hints=("Application Support", "Product Team", "L2 Support"),
    ),
    TaxonomyRuleV2(
        name="Batch, Scheduler & Automation Job Failures",
        description="Scheduled jobs, batch processing, automation runs, cron, Hangfire, Quartz, RPA, and background worker failures.",
        includes=(
            "batch job failed", "scheduled job failed", "scheduler failed", "cron failed",
            "job not triggered", "job stuck", "job running long", "background job",
            "worker failed", "worker stopped", "hangfire", "quartz", "airflow",
            "automation failed", "rpa failed", "bot failed", "bot stuck",
            "retry exhausted", "max retries exceeded", "task failed",
            "nightly job", "daily job", "weekly job", "file processing job",
        ),
        contexts=("batch", "scheduler", "automation", "background processing", "job"),
        excludes=("print job", "user task approval"),
        record_types=("incident", "alert"),
        subcategories=("scheduler", "batch_processing", "worker", "rpa_bot", "retry_failure"),
        assignment_hints=("Application Support", "Automation", "Platform"),
    ),
    TaxonomyRuleV2(
        name="Monitoring, Observability & Alert Noise",
        description="Monitoring alerts, false positives, missing alerts, log/metric/tracing gaps, dashboard alerts, and observability pipeline issues.",
        includes=(
            "monitoring alert", "alert triggered", "false positive", "false alert",
            "alert storm", "alert noise", "no alert generated", "missing alert",
            "threshold breach", "metric missing", "logs missing", "log ingestion failed",
            "trace missing", "apm alert", "synthetic monitor", "heartbeat failed",
            "health check alert", "availability alert", "grafana", "prometheus",
            "datadog", "splunk", "dynatrace", "new relic", "cloudwatch",
        ),
        contexts=("monitoring", "observability", "alert", "logging", "metrics", "apm"),
        excludes=("security alert", "phishing alert", "access review alert"),
        record_types=("alert", "incident"),
        subcategories=("false_positive", "missing_alert", "metric_log_trace", "threshold", "health_check"),
        assignment_hints=("SRE", "Observability", "Platform"),
    ),
    TaxonomyRuleV2(
        name="DevOps, CI/CD & Release Deployment Issues",
        description="Build, deployment, pipeline, artifact, release, rollback, environment, and configuration deployment issues.",
        includes=(
            "build failed", "pipeline failed", "ci failed", "cd failed", "deployment failed",
            "release failed", "rollback failed", "artifact missing", "artifact download failed",
            "package failed", "npm install failed", "maven build failed", "nuget restore",
            "docker build failed", "image build failed", "helm upgrade failed",
            "terraform apply failed", "infrastructure as code", "iac failed",
            "environment variable", "config missing", "configuration mismatch",
            "release blocker", "post deployment issue", "deployment validation failed",
        ),
        contexts=("devops", "cicd", "pipeline", "release", "deployment", "environment"),
        excludes=("application user issue", "business approval workflow"),
        record_types=("incident", "change", "service_request"),
        subcategories=("build", "deployment", "artifact", "iac", "config", "rollback"),
        assignment_hints=("DevOps", "Release", "Platform Engineering"),
    ),
    TaxonomyRuleV2(
        name="Endpoint, Hardware & Peripheral Issues",
        description="Laptop, desktop, mobile device, printer, scanner, monitor, keyboard, mouse, docking, battery, and peripheral issues.",
        includes=(
            "laptop", "desktop", "workstation", "keyboard", "mouse", "monitor",
            "display not detected", "screen flickering", "screen goes blank",
            "display goes blank", "scanner feeder", "scanner feeder jam",
            "battery issue", "battery not charging", "charger", "docking station",
            "dock not working", "usb device", "peripheral", "printer", "printing issue",
            "print queue", "scanner", "scan quality", "document feeder",
            "webcam", "camera not working", "microphone not working", "headset",
            "mobile device", "iphone", "android", "mdm enrollment",
        ),
        contexts=("hardware", "endpoint", "device", "desktop support", "field support"),
        excludes=("server hardware", "vm cpu", "cloud compute"),
        record_types=("incident", "service_request"),
        subcategories=("laptop_desktop", "printer_scanner", "display_dock", "battery", "mobile_mdm", "peripherals"),
        assignment_hints=("Desktop Support", "Endpoint", "Field Services"),
    ),
    TaxonomyRuleV2(
        name="Software Install, Patch & License Requests",
        description="Software installation, upgrade, patching, license assignment, package deployment, and desktop application request issues.",
        includes=(
            "software install", "install software", "application install", "need software",
            "software request", "license request", "license activation", "license expired",
            "license key", "software upgrade", "upgrade request", "patch install",
            "patch failed", "package deployment", "sccm", "intune", "jamf",
            "app catalog", "company portal", "software center", "version upgrade",
        ),
        contexts=("software", "endpoint", "license", "desktop application", "patching"),
        excludes=("server patching", "database patch", "security vulnerability"),
        record_types=("service_request", "incident", "change"),
        subcategories=("install", "upgrade", "patch", "license", "package_deployment"),
        assignment_hints=("Endpoint", "Software Asset", "Service Desk"),
    ),
    TaxonomyRuleV2(
        name="Service Request Fulfillment",
        description="General service requests for new access, equipment, information, onboarding/offboarding, catalog items, and standard fulfillment.",
        includes=(
            "request item", "ritm", "catalog item", "service catalog", "new request",
            "need access", "need laptop", "need monitor", "need software",
            "new hire", "onboarding", "offboarding", "employee transfer",
            "provide access", "create account", "new account", "shared mailbox request",
            "distribution list request", "information request", "how to", "where can i",
            "please provide", "please create", "approval required", "fulfillment task",
            "sctask", "req number",
        ),
        contexts=("service request", "request fulfillment", "catalog", "ritm", "sctask"),
        excludes=("down", "outage", "failed", "error", "not working", "degraded"),
        record_types=("service_request",),
        subcategories=("access_request", "hardware_request", "software_request", "information_request", "onboarding_offboarding"),
        assignment_hints=("Service Desk", "Fulfillment"),
    ),
    TaxonomyRuleV2(
        name="Major Incident, Outage & Service Degradation",
        description="High-impact outages, service down, widespread impact, degradation, SLA breach, and major incident events.",
        includes=(
            "major incident", "sev1", "sev 1", "sev2", "sev 2", "p1", "p2",
            "service down", "system down", "application down", "website down",
            "outage", "complete outage", "partial outage", "widespread issue",
            "multiple users affected", "all users affected", "business critical",
            "production down", "prod down", "severe degradation", "service degradation",
            "sla breach", "customer impact", "revenue impact", "unable to process",
        ),
        contexts=("incident", "major incident", "outage", "production", "severity", "priority"),
        excludes=("planned maintenance", "scheduled downtime", "change window"),
        record_types=("incident", "alert"),
        subcategories=("outage", "degradation", "p1_p2", "sla_breach", "customer_impact"),
        assignment_hints=("Major Incident", "SRE", "Operations"),
    ),
    TaxonomyRuleV2(
        name="Identity Directory Sync & Account Lifecycle Issues",
        description="Directory synchronization, account lifecycle, HR identity feed, SCIM, joiner-mover-leaver, and identity attribute issues.",
        includes=(
            "directory sync", "ad sync", "azure ad connect", "entra connect",
            "identity sync", "scim", "user provisioning sync", "account creation failed",
            "account not created", "duplicate account", "disabled account", "account disabled",
            "stale account", "orphaned account", "attribute mismatch", "manager field incorrect",
            "department field incorrect", "upn mismatch", "email attribute", "hr feed",
            "joiner mover leaver", "jml", "new hire account", "termination feed",
            "offboarding failed", "user lifecycle", "identity lifecycle",
        ),
        contexts=("identity", "iam", "directory", "active directory", "entra", "azure ad", "hris"),
        excludes=("normal access request", "password reset", "license request"),
        record_types=("incident", "service_request"),
        subcategories=("directory_sync", "account_lifecycle", "hr_feed", "attribute_mismatch", "jml"),
        assignment_hints=("IAM", "Identity", "Directory Services"),
    ),
    TaxonomyRuleV2(
        name="Endpoint Management, Compliance & Remote Access Issues",
        description="Endpoint management issues involving MDM, compliance, VPN posture, device certificates, Intune, Jamf, SCCM, and remote wipe/enrollment.",
        includes=(
            "device compliance", "endpoint compliance", "compliance policy", "non compliant device",
            "mdm", "mdm enrollment", "intune enrollment", "jamf enrollment",
            "company portal", "device registration", "device not registered",
            "device certificate", "certificate profile", "configuration profile",
            "remote wipe", "lost device", "bitlocker", "filevault", "defender for endpoint",
            "edr sensor", "sccm client", "software center", "patch compliance",
            "vpn posture", "conditional access device", "managed device",
        ),
        contexts=("endpoint", "device management", "mdm", "intune", "jamf", "sccm"),
        excludes=("user login failed", "network vpn outage", "server patching"),
        record_types=("incident", "service_request", "alert"),
        subcategories=("mdm_enrollment", "device_compliance", "configuration_profile", "remote_wipe", "patch_compliance"),
        assignment_hints=("Endpoint", "Desktop Support", "Device Management"),
    ),
    TaxonomyRuleV2(
        name="Print, Scan & Document Output Issues",
        description="Printer, scanner, print queue, label printing, document rendering, document generation, and physical output issues.",
        includes=(
            "printer offline", "printer not working", "printing issue", "print queue",
            "print job stuck", "print spooler", "label printer", "badge printer",
            "barcode printer", "paper jam", "toner", "scanner not working",
            "scan quality", "document feeder", "scan to email", "scan to folder",
            "document generation failed", "document rendering", "pdf generation failed",
            "template rendering", "invoice print", "shipping label", "receipt print",
        ),
        contexts=("printing", "scanner", "document output", "endpoint", "facilities"),
        excludes=("batch job", "file transfer", "email attachment"),
        record_types=("incident", "service_request"),
        subcategories=("printer", "scanner", "print_queue", "document_generation", "label_printing"),
        assignment_hints=("Desktop Support", "Print Services", "Facilities IT"),
    ),
    TaxonomyRuleV2(
        name="Procurement, Purchasing & Supplier Workflow Issues",
        description="Procurement workflow issues involving purchase orders, requisitions, supplier onboarding, approvals, contracts, sourcing, and receiving.",
        includes=(
            "purchase order", "po approval", "po mismatch", "po blocked",
            "purchase requisition", "requisition approval", "procurement workflow",
            "purchasing workflow", "supplier onboarding", "vendor onboarding",
            "supplier record", "vendor record", "sourcing request", "contract approval",
            "contract workflow", "goods receipt", "receiving issue", "three way match",
            "catalog item unavailable", "supplier portal", "vendor portal access",
        ),
        contexts=("procurement", "purchasing", "supplier", "vendor management", "sourcing"),
        excludes=("invoice payment", "payment failed", "billing error"),
        record_types=("incident", "service_request"),
        subcategories=("purchase_order", "requisition", "supplier_onboarding", "contract", "receiving"),
        assignment_hints=("Procurement", "Purchasing", "Supplier Management"),
    ),
    TaxonomyRuleV2(
        name="Finance, Billing & Payment Processing Issues",
        description="Billing, invoice, payment, refund, reconciliation, purchase order, expense, tax, and finance transaction issues.",
        includes=(
            "payment failed", "payment processing", "payment gateway", "card declined",
            "refund failed", "invoice mismatch", "invoice error", "billing error",
            "billing address", "tax calculation", "tax code", "expense report",
            "purchase order", "po approval", "po mismatch", "vendor invoice",
            "reconciliation mismatch", "settlement failed", "payment batch",
            "invoice reconciliation", "invoice reconciliation mismatch", "invoice reconciliation process",
            "accounts payable", "accounts receivable", "general ledger", "gl posting",
            "finance posting", "duplicate charge", "chargeback",
        ),
        contexts=("finance", "billing", "payment", "invoice", "procurement", "erp"),
        excludes=("database transaction", "application transaction failed"),
        record_types=("incident", "service_request"),
        subcategories=("payment", "billing", "invoice", "purchase_order", "reconciliation", "erp_posting"),
        assignment_hints=("Finance Systems", "ERP", "Billing Support"),
    ),
    TaxonomyRuleV2(
        name="HR, Payroll & Workforce System Issues",
        description="HR, payroll, benefits, timekeeping, onboarding, recruiting, learning, and workforce system issues.",
        includes=(
            "payroll error", "payroll failed", "payslip", "salary incorrect",
            "timecard", "timesheet", "time entry", "clock in", "clock out",
            "leave balance", "pto balance", "benefits enrollment", "open enrollment",
            "employee onboarding", "onboarding checklist", "background check",
            "candidate profile", "recruiting", "offer letter", "learning assignment",
            "training module", "performance review", "hr case", "worker profile",
        ),
        contexts=("hr", "payroll", "workforce", "hris", "hcm", "workday", "successfactors"),
        excludes=("account onboarding", "device onboarding", "identity lifecycle"),
        record_types=("incident", "service_request"),
        subcategories=("payroll", "timekeeping", "benefits", "onboarding", "recruiting", "learning"),
        assignment_hints=("HR Systems", "Payroll", "People Operations"),
    ),
    TaxonomyRuleV2(
        name="Facilities, Badge & Physical Access Issues",
        description="Office facilities, badge access, door access, conference rooms, visitor management, building systems, and physical workspace issues.",
        includes=(
            "badge access", "door access", "access card", "card reader",
            "turnstile", "visitor management", "visitor badge", "conference room",
            "meeting room display", "room booking", "av equipment", "projector",
            "desk booking", "hot desk", "parking access", "elevator",
            "hvac", "temperature control", "building access", "facility request",
            "office move", "seat assignment", "security desk",
        ),
        contexts=("facilities", "physical access", "badge", "office", "workplace"),
        excludes=("application access", "network access", "privileged access"),
        record_types=("incident", "service_request"),
        subcategories=("badge_access", "visitor_management", "room_booking", "av_equipment", "building_system"),
        assignment_hints=("Facilities", "Physical Security", "Workplace Services"),
    ),
    TaxonomyRuleV2(
        name="Vendor, SaaS & Third-Party Service Issues",
        description="Third-party SaaS, vendor platform, external dependency, subscription, support escalation, and vendor outage issues.",
        includes=(
            "vendor outage", "third party outage", "saas outage", "external dependency",
            "vendor portal", "vendor api", "vendor integration", "partner system",
            "subscription expired", "tenant issue", "support escalation", "vendor ticket",
            "service provider outage", "downstream vendor", "upstream vendor",
            "salesforce", "servicenow", "workday", "concur", "docusign",
            "jira cloud", "github outage", "microsoft 365 outage", "google workspace outage",
        ),
        contexts=("vendor", "saas", "third party", "external service", "supplier"),
        excludes=("internal api", "internal application", "normal software install"),
        record_types=("incident", "service_request", "alert"),
        subcategories=("vendor_outage", "saas_platform", "subscription", "support_escalation", "external_dependency"),
        assignment_hints=("Vendor Management", "SaaS Operations", "Application Support"),
    ),
)


def _normalized_phrase(value: str) -> str:
    return value.replace("_", " ").strip()


def _unique(values: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(_normalized_phrase(value) for value in values if _normalized_phrase(value)))


def _taxonomy_v2_as_rules(rules: tuple[TaxonomyRuleV2, ...]) -> tuple[TaxonomyRule, ...]:
    return tuple(
        TaxonomyRule(
            name=rule.name,
            description=rule.description,
            patterns=_unique(rule.includes),
            category_aliases=_unique(rule.contexts + rule.assignment_hints),
            excludes=_unique(rule.excludes),
        )
        for rule in rules
    )


DEFAULT_TAXONOMY = _taxonomy_v2_as_rules(DEFAULT_TAXONOMY_V2)
